config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :passwords, only: [:new, :create, :update] do
    get 'edit', on: :collection
  end

  resources :sessions, only: [:create, :destroy]

  concern :pagination do
    get 'page/:page' => :index, as: :page, on: :collection
  end

  resources :users, except: [:new, :destroy], concerns: :pagination do
    collection do
      get 'account_activation'
      post 'update_state'
    end
    member do
      get 'contribution'
      post 'update_image'
      get 'projects' => 'projects#index'
    end
  end

  resources :projects, concerns: :pagination do
    collection do
      get ':catagory' => :view_all, as: :catagory, 
          constraints: -> (request) { PROJECT_CATAGORIES.include?(request.path_parameters[:catagory]) }
    end
    member do
      post 'update_status'
      scope 'transactions', controller: :transactions do
        post 'new', as: 'new_transaction_for'
        get 'build', as: 'build_transaction_for'
        post 'create', as: 'create_transaction_for'
        get 'success', as: 'success_transaction_for'
      end
    end
  end

  resources :transactions, only: [:index] do
    get 'download_receipt/:stripeToken' => :download_receipt, as: :download_receipt, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  namespace :apis do
    get 'projects' => 'projects#index', defaults: { format: 'JSON' }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  DEFAULT_DOCUMENTS_COUNT = 3

  has_one :profile, dependent: :destroy
  has_many :documents, as: :attachable, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :transactions
  # has_many :texts
  # has_many :circles
  # has_many :friends, through: :circles
  has_and_belongs_to_many :friends, join_table: :friends, class_name: 'User', foreign_key: :user_id, association_foreign_key: :friend_id, after_add: :create_friend

  accepts_nested_attributes_for :profile, :documents

  has_attached_file :image,
    url: ":rails_root/public/:class/:attachment/:id/:basename_:style.:extension",
    default_url: ":rails_root/public/:class/:attachment/default.jpg",
    styles: {
      thumb: ['100x100#', :jpg],
      medium: [ '150x150!', :jpg],
      large: ['600>', :jpg]
    },
    default_style: :medium
  
  validates_attachment :image, content_type: { content_type: ["image/jpeg"] }  
  has_secure_password

  validates :name, :email, presence: true
  validates :password_confirmation, presence: true, unless: [:token_type, :account_updation]
  validates :password, presence: true, on: [:update], unless: [:token_type, :account_updation]
  validates :password, length: { minimum: 8 }, allow_blank: true
  validates_with EmailValidator, if: :email?, on: [:create], allow_blank: true
  validates :email, uniqueness: true, on: [:create], allow_blank: true
  validates :reset_password_token, :account_activation_token, uniqueness: true, allow_nil: true, if: :token_type

  before_create :set_defaults, unless: :role?
  after_save :send_mail, if: :token_type
  before_save :nullify_password_tokens, if: :is_password_changed

  attr_accessor :token_type, :account_updation, :is_password_changed
  delegate :phone_no, :permanent_address, :current_address, :permanent_account_number, to: :profile, allow_nil: true

  scope :load_users, -> (users_count, page_no) { where(role: :user).limit(users_count).offset(users_count * (page_no - 1)).order(created_at: :desc) }
  scope :count_all_users, -> { where(role: :user).count }
  ##################################
  
  # before_validation :b4_v
  # before_create :b4_c
  # before_save :b4_s
  # before_update :b4_u
  # before_destroy :b4_d

  # around_save :around_s
  # around_create :around_c
  # around_destroy :around_d

  # after_find :after_f
  # after_initialize :after_i
  # after_touch :after_t

  # after_validation :after_v
  # after_create :after_c, prepend: true
  # after_save :after_s
  # after_update :after_u
  # after_destroy :after_d

  # after_commit :after_comm
  # after_rollback :after_roll

  # #################################
  
  # def create_friend(record)
  #   record.friends << self if record.friends.exclude?(self)
  # end

  def nullify_password_tokens
    self.reset_password_token, self.reset_password_token_generated_at = nil, nil
  end

  def update_password(user_params, is_password_changed = false)
    self.is_password_changed = is_password_changed
    update(user_params)
  end

  def generate_reset_password_token
    self.token_type, self.reset_password_token, self.reset_password_token_generated_at = 'reset_password', *generate_token
    save
  end

  def generate_account_activation_token
    self.token_type, self.account_activation_token, self.account_activation_token_generated_at = 'account_activation', *generate_token
    save
  end

  def activate_account
    update(is_activated: true, account_activation_token: nil, account_activation_token_generated_at: nil)
  end

  def update_account(update_params)
    self.account_updation = true
    update(update_params)
  end

  def build_associated_objects
    build_profile unless profile
    unless documents.present?
      DEFAULT_DOCUMENTS_COUNT.times do |index|
        documents.build(attachable_subtype: Document::SUBTYPES[index])
      end
    end
  end

  def profile_complete?
    return false unless profile && profile.complete?
    documents.length == DEFAULT_DOCUMENTS_COUNT
  end

  def get_attachment(type)
    attachment = documents.where(attachable_subtype: type)
    attachment[0].attachment_file_name if attachment.present?
  end

  def contributions
    transactions.eager_load(:project).order(created_at: :desc)
  end
  
private

  def send_mail
    UserMailer.send("send_#{token_type}_mail".intern, self).deliver_now
  end

  def set_defaults
    self.role = 'user'
  end

  def generate_token
    [BCrypt::Password.create(SecureRandom.hex(5)), Time.current]
  end

  # def b4_v
  #   p "before validation of Text"
  # end
  # def b4_c
  #   p "before create of Text"
  # end
  # def b4_s
  #   p "before save  of Text"
  # end
  # def b4_u
  #   p "before update of Text"
  # end
  # def b4_d
  #   p "before destroy of Text"
  # end
  # def around_c
  #   p "before yield in around_create of Text"
  #   yield
  #   p "after yield in around_create of Text"
  # end
  # def around_s
  #   p "before yield in around save of Text"
  #   yield
  #   p "after yield in around save of Text"
  # end
  # def around_d
  #   p "before yield in around destroy of Text"
  #   yield
  #   p "after yield in around destroy of Text"
  # end
  # def after_s
  #   p "after save of Text"
  # end
  # def after_c
  #   p "after create of Text"
  # end
  # def after_d
  #   p "after destroy of Text"
  # end
  # def after_v
  #   p "after validation of Text"
  # end
  # def after_f
  #   p "after find of Text"
  # end
  # def after_i
  #   p "after initialize of Text"
  # end
  # def after_t
  #   p "after touch of Text"
  # end
  # def after_u
  #   p "after update of Text"
  # end
  # def after_comm
  #   p "after commit of Text"
  # end
  # def after_rollback
  #   p "after rollback of Text"
  # end
  # def after_roll
  #   p "after rollback of Text"
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:show, :edit, :index]
  before_action :verify_activation_token, only: [:account_activation]
  before_action :admin_authorization, :set_pagination_defaults, :validate_page_request, only: [:index]
  before_action :find_user_from_id, only: [:update_state, :show]
  before_action :user_authorization_for_edit, only: [:edit, :update]

  def index
    @users = User.load_users(USERS_PER_PAGE, params[:page])
  end

  def create
    @user = User.new(signup_params)
    respond_to do |format|
      if @user.generate_account_activation_token
        flash[:notice] = t(:account_created)
        format.json { render json: { redirect_url: root_url } }
      else
        format.json { render json: { errors: @user.errors.messages.to_h } }
      end
    end
  end

  def show
    render
  end

  def edit
    current_user.build_associated_objects
  end

  def account_activation
    flash[:notice] = @user.activate_account ? t(:account_activated)  : t(:request_failure)
    redirect_to :root
  end

  def update_state
    respond_to do |format|
      @user.toggle!(:is_activated)
      format.json { render json: { state: @user.is_activated? } }
    end
  end

  def update
    current_user.update_account(update_params) ? after_update : (render 'edit')
  end

  def contribution
    @contributions = current_user.contributions
  end

  def update_image
    current_user.update_account(image_params)
    @user = current_user
    render 'show'
  end

  private

  def after_update
    session[:amount] ? (redirect_to build_transaction_for_project_url(session[:project_id])) : (redirect_to :user, notice: 'Account has been updated successfully')
  end

  def verify_activation_token
    unless @user = User.find_by(account_activation_token: params[:token])
      redirect_to :root, notice: t(:invalid_request)
    end
  end

  def admin_authorization
    (redirect_to :root) unless admin?
  end

  def find_user_from_id
    redirect_to :root, notice: not_found unless @user = User.find_by(id: params[:id])
  end

  def not_found
    t(:not_found, object: 'user')
  end

  def validate_page_request
    if params[:page] > @total_pages || params[:page] < 1
      flash.now[:notice] = not_found
      render
    end
  end

  def set_pagination_defaults
    params[:page] = params[:page] ? params[:page].to_i : 1
    @total_pages = (User.count_all_users.to_f / USERS_PER_PAGE).ceil
  end

  def user_authorization_for_edit
    redirect_to :root unless current_user.id == params[:id].to_i
  end
  
  def signup_params
    params.permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, profile_attributes: [:id, :phone_no, :current_address, :permanent_address, :permanent_account_number],
                                 documents_attributes: [:attachable_subtype, :attachment, :id] )
  end

  def image_params
    params.require(:user).permit(:image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def generate_change_user_state_link(user)
    user.is_activated ? generate_ajax_href(t(:deactivate), user.id) : generate_ajax_href(t(:activate), user.id)
  end

  def generate_ajax_href(text, user_id)
    link_to(text, update_state_users_url, id: user_id, class: 'user state')
  end

  def no_of_documents
    @total_documents ||= @user.documents.size
  end

  def privileged?
  	admin? || (current_user.id == params[:id].to_i)
  end

end

app/views/users/_signup.html.erb
<h2 align="center"><%= t(:signup_form) %></h2>
<div id="dialog">
  <%= form_for(User.new) do |f| %>
    <div class="required">
      <%= f.label :name, t(:name) %><br>
      <%= f.text_field :name, required: true %>
    </div>
    <div class="required">
      <%= f.label :email, t(:email) %><br>
      <%= f.email_field :email, required: true %>
    </div>
    <div class="required">
      <%= f.label :password, t(:password) %><br>
      <%= f.password_field :password, required: true %>
    </div>
    <div class="required">
      <%= f.label :password_confirmation, t(:confirm_password) %><br>
      <%= f.password_field :password_confirmation, required: true %>
    </div>
    <div class="actions">
      <%= f.submit t(:register), 'data-disable-with' => 'Signing up..' %>
    </div>
  <% end %> 
</div>

app/views/users/contribution.html.erb
<% if @contributions.present? %>
  <table class="table">
    <tr>
      <th><%= t(:project) %></th>
      <th><%= t(:amount) %></th>
      <th><%= t(:invested_on) %> (Date&Time)</th>
    </tr>
    <% @contributions.each do |contribution| %>
      <tr>
        <td>
          <%= link_to contribution.project.title, project_url(contribution.project) %>
        </td>
        <td>
          <%= contribution.amount %>
        </td>
        <td>
          <%= contribution.created_at.in_time_zone('Kolkata') %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class='notice'><p><%= t(:not_contributed) %></p></div>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, t(:edit_profile) %>
<%= form_for current_user do |f| %>
<%= content_for :javascript do %>
  <%= javascript_include_tag 'edit_profile' %>
<% end %>
<%= render partial: 'shared/errors', locals: { form: current_user } %>
  <table class="table">
    <tr class="required">
      <td><%= f.label :name, t(:name) %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <%= f.fields_for :profile_attributes, current_user.profile do |profile| %>
      <tr class="required">
        <td><%= profile.label :phone_no, t(:phone_no) %></td>
        <td><%= profile.telephone_field(:phone_no, required: true) %></td>
      </tr>
      <tr class="required">
        <td><%= profile.label :current_address, t(:current_address) %></td>
        <td><%= profile.text_field(:current_address, required: true) %></td>
      </tr>
      <tr>
        <td class="required"><%= profile.label :permanent_address, t(:permanent_address) %></td>
        <td>
          <%= profile.text_field(:permanent_address, required: true) %>
          <%= check_box_tag(:same_as_current) %>
          <%= label_tag(:same_as_current, t(:same_as_current)) %>
        </td>
      </tr>
      <tr class="required">
        <td><%= profile.label(:permanent_account_number, 'PAN') %></td>
        <td><%= profile.text_field :permanent_account_number, required: true %></td>
      </tr>
    <% end %>
    <%= f.fields_for :documents do |document_form| %>
      <tr>
        <td>
          <%= document_form.label :attachment, "#{ document_form.object.attachable_subtype.titleize }" + ' ' + t(:attachment) %>
        </td>
        <td>
          <%= document_form.file_field(:attachment) %>
          <%= document_form.hidden_field :attachable_subtype, value: document_form.object.attachable_subtype %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= f.submit t(:save_changes), 'data-disable-with' => 'Saving..' %>
<% end %>

app/views/users/index.html.erb
<% content_for :title, 'Users' %>
<% content_for :javascript do %>
  <% javascript_include_tag 'index_page' %>
<% end %>
<% if @users %>
  <div id='users'>
    <table class="table">
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t(:email) %></th>
        <th><%= t(:actions) %></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to t(:show), user %>
            <%= generate_change_user_state_link(user) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <% add_pagination(:page_users_url) %>
<% end %>

app/views/users/show.html.erb
<% content_for :title, 'User' %>
<% content_for :javascript do %>
  <% javascript_include_tag :image %>
<% end %>

<%= render partial: 'shared/errors', locals: { form: current_user } %>

<div id="user_image">
  <div id="profile_pic">
    <%= image_tag @user.image.url(:medium) %>
  </div>
  
  <%= form_for :user, url: update_image_user_url(current_user), html: { class: 'edit_profile_pic' } do |f| %>
    <%= f.file_field :image, required: true %>
    <%= submit_tag :Save %>
    <%= link_to :cancel, 'javascript:', class: 'cancel btn btn-primary' %>
  <% end %>

  <% if current_user.id == @user.id %>
    <%= form_tag 'javascript:', class: 'change inline' do %>
      <%= submit_tag :change %>
    <% end %>

    <div class="inline edit_profile_links">
      <%= link_to 'Edit Profile', edit_user_url(@user), method: :get, 'data-disable-with' => 'Processing..', class: 'btn btn-primary' %>
      <%= link_to 'Reset Password', edit_passwords_url, method: :get, 'data-disable-with' => 'Processing..', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<div id="user_info">
  <table class="table">
    <tr>
      <th><%= t(:name) %></th>
      <td><%= @user.name.capitalize || 'NA' %></td>
    </tr>
    <tr>
      <th><%= t(:email) %></th>
      <td><%= @user.email || 'NA' %></td>
    </tr>
    <% if privileged? %>
      <tr>
        <th><%= t(:phone_no) %></th>
        <td><%= @user.phone_no || 'NA' %></td>
      </tr>
      <tr>
        <th><%= t(:permanent_address) %></th>
        <td><%= @user.permanent_address || 'NA' %></td>
      </tr>
      <tr>
        <th><%= t(:current_address) %></th>
        <td><%= @user.current_address || 'NA' %></td>
      </tr>
      <tr>
        <th><%= t(:permanent_account_number) %></th>
        <td><%= @user.permanent_account_number || 'NA' %></td>
      </tr>
      <tr>
        <th><%= "PAN_#{ t(:attachment) }" %></th>
        <td><%= @user.get_attachment('PAN') || 'NA' %></td>
      </tr>
      <tr>
        <th><%= t(:current_address) + ' ' + t(:attachment) %></th>
        <td><%= @user.get_attachment('current_address') || 'NA' %></td>
      </tr>
      <tr>
        <th><%= t(:permanent_address) + ' ' + t(:attachment) %></th>
        <td><%= @user.get_attachment('permanent_address') || 'NA' %></td>
      </tr>
    <% end %>
    <tr>
      <th><%= t(:projects) %></th>
      <td>
        <% if @user.projects.present? %>
          <% @user.projects.each do |project| %>
            <%= link_to project.title.humanize, project_url(project) %>
            <br>
          <% end %>
        <% else %>
          NA
        <% end %>
      </td>
    </tr>
  </table>
</div>
<% if @user.contributions.present? %>
  <div class="user_contributions">
    <h2 align="center"> <%= t(:contribution) %> </h2>
    <table class="table">
      <tr>
        <th><%= t(:project) %></th>
        <th><%= t(:time_of_contribution) %></th>
        <th><%= t(:amount) %></th>
      </tr>
        <% @user.contributions.each do |contribution| %>
          <tr>
            <td><%= link_to contribution.project.title.humanize, project_url(contribution.project) %></td>
            <td><%= contribution.created_at.in_time_zone('Kolkata') %></td>
            <td><%= contribution.amount %></td>
          </tr>
        <% end %>
    </table>
  </div>
<% end %>