config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :passwords, only: [:new, :create, :update] do
    get 'edit', on: :collection
  end

  resources :sessions, only: [:create, :destroy]

  concern :pagination do
    get 'page/:page' => :index, as: :page, on: :collection
  end

  resources :users, except: [:new, :destroy], concerns: :pagination do
    collection do
      get 'account_activation'
      post 'update_state'
    end
    member do
      get 'contribution'
      post 'update_image'
      get 'projects' => 'projects#index'
    end
  end

  resources :projects, concerns: :pagination do
    collection do
      get ':catagory' => :view_all, as: :catagory, 
          constraints: -> (request) { PROJECT_CATAGORIES.include?(request.path_parameters[:catagory]) }
    end
    member do
      post 'update_status'
      scope 'transactions', controller: :transactions do
        post 'new', as: 'new_transaction_for'
        get 'build', as: 'build_transaction_for'
        post 'create', as: 'create_transaction_for'
        get 'success', as: 'success_transaction_for'
      end
    end
  end

  resources :transactions, only: [:index] do
    get 'download_receipt/:stripeToken' => :download_receipt, as: :download_receipt, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  namespace :apis do
    get 'projects' => 'projects#index', defaults: { format: 'JSON' }
  end
end

app/views/shared/_errors.html.erb
<% if form.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(form.errors.count, t(:error)) %> <%= t(:prohibited_record_save) %>:</h2>
    <ul>
    <% form.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b><%= t(:crowd_funding).upcase %></b></a>
    </div>
    <div class="modal fade bs-example-modal-lg" id="login_form" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div id="login_container">
            <%= (render 'sessions/login') unless current_user %>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-lg" id="signup_form" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div id="signup_container">
            <%= (render 'users/signup') unless current_user %>
          </div>
        </div>
      </div>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% unless current_page?(root_url) %>
          <li><%=link_to t(:home), root_path, id: 'home_anchor' %></li>
        <% end %>
        <% if current_user %>
          <li><%= (link_to t(:users), users_path, 'data-disable-with' => 'Users', id: 'users_anchor') if admin? %></li>
          <li><%= link_to t(:account), user_path(current_user), 'data-disable-with' => 'Account', id: 'account_anchor' %></li>
          <li><%= link_to t(:project), projects_path, 'data-disable-with' => 'Project' %></li>
          <li><%= link_to t(:transactions), :transactions if admin? %></li>
          <li><%= link_to t(:contribution), contribution_user_path(current_user), 'data-disable-with' => 'Contributions...' %></li>
          <li><%= link_to t(:logout), session_path(current_user), method: :delete, 'data-disable-with' => 'Processing..' %></li>
        <% else %>
          <li>
            <a id="signup_anchor" data-toggle="modal" data-target=".bs-example-modal-sm" href='#'><%= t(:signup) %></a>
          </li>
          <li>
            <a id="login_anchor" data-toggle="modal" data-target=".bs-example-modal-sm" href='#' ><%= t(:login) %></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>