config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :passwords, only: [:new, :create, :update] do
    get 'edit', on: :collection
  end

  resources :sessions, only: [:create, :destroy]

  concern :pagination do
    get 'page/:page' => :index, as: :page, on: :collection
  end

  resources :users, except: [:new, :destroy], concerns: :pagination do
    collection do
      get 'account_activation'
      post 'update_state'
    end
    member do
      get 'contribution'
      post 'update_image'
      get 'projects' => 'projects#index'
    end
  end

  resources :projects, concerns: :pagination do
    collection do
      get ':catagory' => :view_all, as: :catagory, 
          constraints: -> (request) { PROJECT_CATAGORIES.include?(request.path_parameters[:catagory]) }
    end
    member do
      post 'update_status'
      scope 'transactions', controller: :transactions do
        post 'new', as: 'new_transaction_for'
        get 'build', as: 'build_transaction_for'
        post 'create', as: 'create_transaction_for'
        get 'success', as: 'success_transaction_for'
      end
    end
  end

  resources :transactions, only: [:index] do
    get 'download_receipt/:stripeToken' => :download_receipt, as: :download_receipt, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  namespace :apis do
    get 'projects' => 'projects#index', defaults: { format: 'JSON' }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  DEFAULT_PROJECTS_COUNT = 4
  DEFAULT_CATAGORY_PROJECTS_COUNT = 4
  MORE_CATAGORY_PROJECTS_COUNT = 4
  DEFAULT_FILTER = 'Charity'
  DEFAULT_SORT = 'Popularity'
  PERMITTED_STATUS = [:Published, :Canceled, :Unpublished, :Reopen, :Expired, :Completed]

  TYPES = ['Charity', 'Investment']

  attr_writer :user_minimum_contribution
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :documents,-> { where(attachable_subtype: 'document') }, as: :attachable, dependent: :destroy
  has_many :images,-> { where(attachable_subtype: 'image') }, as: :attachable, class_name: "Document", dependent: :destroy
  has_many :transactions
  has_many :urls
  has_many :texts
  
  validates :title, :kind, :description, :end_date, :total_amount, presence: true
  validate :acceptable_total_amount, if: :total_amount?
  validates :total_amount, numericality: { greater_than: 100000 }, on: :create

  accepts_nested_attributes_for :documents, :images, reject_if: proc { |attributes| attributes['attachment'].blank? }
  
  scope :fetch_for_current_page, -> (projects_count, page_no) { limit_selection(projects_count, projects_count * (page_no - 1)).order(created_at: :desc) }
  scope :limit_selection, -> (limit, offset) { limit(limit).offset(offset) }

  scope :load_published, -> { where(status: 'Published') }
  scope :load_from_kind, -> (kind) { load_published.where(kind: (kind ||= DEFAULT_FILTER)) }

  def self.load_maximum_completed(kind=nil)
    load_from_kind(kind).eager_load(:transactions).to_a.sort_by { |p| p.percentage_completed }.reverse
  end

  def self.load_recently_created(limit=DEFAULT_PROJECTS_COUNT, offset=0, kind=nil)
    load_from_kind(kind).order(created_at: :desc).limit_selection(limit, offset)
  end

  def self.load_fully_completed(kind=nil)
    load_from_kind(kind).eager_load(:transactions).to_a.select { |p| p.percentage_completed == 100 }
  end

  def user_maximum_contribution
    @user_maximum_contribution ||= total_amount - amount_funded
  end

  def user_minimum_contribution
    if total_amount
      @user_minimum_contribution ||= total_amount / 10
      @user_minimum_contribution = @user_maximum_contribution if @user_minimum_contribution.to_i > user_maximum_contribution
    end
    @user_minimum_contribution
  end

  def percentage_completed
    @percentage_compteted ||= ( amount_funded / total_amount.to_f) * 100
  end

  def amount_funded
    transactions.to_a.sum(&:amount)
  end

  def get_contributers_count
    transactions.to_a.uniq{ |t| t.user_id }.count
  end

  def update_status(new_status)
    if status_valid?(new_status.intern)
      last_status = status;
      send_cancellation_mail(last_status) if update(status: new_status)
      true
    end
  end
  
  def as_json(options={})
    { title: title, type: kind, percentage_completed: percentage_completed, amount_funded: amount_funded }
  end

  def published?
    status.eql?('Published')
  end

private

  def send_cancellation_mail(last_status)
    if last_status.eql?('Published') && status.eql?('Canceled')
      send_mail_to_contributors
    end
  end

  def status_valid?(status)
    status && PERMITTED_STATUS.include?(status)
  end

  def send_mail_to_contributors
    transactions.eager_load(:user, :project).each do |transaction|
      if transaction.refund
        UserMailer.send_project_cancelation_mail(transaction).deliver_now
      end
    end
  end

  def acceptable_total_amount
    errors.add(:total_amount, 'must be in multiple of 100') unless (total_amount % 100).zero?
  end

end

app/controllers/apis/projects_controller.rb
class Apis::ProjectsController < ActionController::Base
  before_action :load_projects, only: [:index]

  def index
    render json: @projects.as_json
  end

private

  def load_projects
    @projects = Project.load_published
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :user_authorized_for_edit?, :created_by_current_user?, :current_project

  before_action :authorize_user, only: [:index, :new, :edit, :update]
  before_action :build_project_attachments, only: [:new]
  before_action :set_pagination_defaults, :load_projects, only: [:index]
  before_action :load_project, only: [:edit, :update, :show]
  before_action :authorize_user_for_edit, only: [:edit, :update]
  before_action :check_project_accessibility, only: [:show]

  def index
    flash.now[:notice] = t(:not_found, object: 'project') unless @projects.present?
  end

  def new
    render
  end

  def create
    @project = current_user.projects.build(project_params)
    @project.save ? after_create : (render 'new')
  end

  def show
    render
  end

  def edit
    render
  end

  def update
    if @project.update(project_params)
      redirect_to :root, notice: t(:project_updated)
    else
      render 'edit'
    end
  end

  def update_status
    if current_project
      current_project.update_status(params[:status]) ? (head 200) : (head 400)
    else
      head 404
    end
  end

  def view_all
    @projects = load_projects_catagory_wise
    @projects = sort if @projects.present?
    (render layout: false) if params_present?
  end
  
private

  def params_present?
    params[:offset] || params[:filter] || params[:sort_by]
  end 

  def load_projects_catagory_wise
    limit,offset = *get_limit_and_offset
    
    case params[:catagory]
    when "maximum_completed"
      Project.load_maximum_completed(params[:filter])[offset, limit]
    when "recently_created"
      Project.load_recently_created(limit, offset, params[:filter])
    when "fully_completed"
      Project.load_fully_completed(params[:filter])[offset, limit]
    end

  end

  def get_limit_and_offset
    limit = get_limit
    offset = get_offset
    [limit,offset]
  end

  def get_limit
    params[:offset] ? Project::MORE_CATAGORY_PROJECTS_COUNT : Project::DEFAULT_CATAGORY_PROJECTS_COUNT
  end

  def get_offset
    params[:offset] ? Project::DEFAULT_CATAGORY_PROJECTS_COUNT + (Project::MORE_CATAGORY_PROJECTS_COUNT * (params[:offset].to_i - 1)) : 0
  end

  def filter
    @filter = params[:filter] ? params[:filter] : Project::DEFAULT_FILTER
    @projects.select! { |project| project.kind.eql?(@filter) }
  end

  def sort
    @sort_by = params[:sort_by] ? params[:sort_by] : Project::DEFAULT_SORT
    case @sort_by
    when 'Popularity'
      @projects.sort_by { |project| project.get_contributers_count }.reverse
    when 'Recent'
      @projects.sort_by { |project| project.created_at }.reverse
    when 'Ending at'
      @projects.sort_by { |project| project.end_date }
    when params[:catagory].titleize
      @projects
    end
  end

  def authorize_user_for_edit
    redirect_to :root unless user_authorized_for_edit?
  end

  def created_by_current_user?
    @is_owner ||= (current_project.user_id == current_user.id) if current_user
  end

  def user_authorized_for_edit?
    created_by_current_user? && !current_project.published?
  end

  def after_create
    current_user.profile_complete? ? (redirect_to :root, notice: t(:project_created)) : (redirect_to edit_user_url(current_user), notice: t(:request_profile_completion))
  end

  def load_project
    (redirect_to :root, notice: "Project Not Found") unless current_project
  end

  def current_project
    @project ||= Project.find_by(id: params[:id])
  end

  def load_projects
    @projects = admin? ? load_projects_for_current_page : load_user_projects
  end

  def load_user_projects
    params[:id] ? User.find_by(id: params[:id]).try(:projects) : current_user.projects
  end

  def load_projects_for_current_page
    Project.fetch_for_current_page(PROJECTS_PER_PAGE, params[:page]) if requested_page_valid?
  end

  def requested_page_valid?
    params[:page] <= @total_pages && params[:page] >= 1
  end

  def check_project_accessibility
    unless admin?
      (redirect_to :root, notice: 'Access Denied') unless project_accessible?
    end
  end

  def project_accessible?
    current_project.published? || created_by_current_user?
  end

  def set_pagination_defaults
    if admin?
      params[:page] = params[:page] ? params[:page].to_i : 1
      @total_pages = (Project.all.count.to_f / PROJECTS_PER_PAGE).ceil
    end
  end

  def build_project_attachments
    @project = Project.new
    @project.documents.build
    @project.images.build
  end

  def project_params
    params.require(:project).permit(:id, :kind, :title, :description, :end_date, :total_amount, :video_link, :user_minimum_contribution,
                                      documents_attributes: [:attachment, :attachable_subtype, :id],
                                      images_attributes: [:attachment, :attachable_subtype, :id] )
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def add_link_to_publish(project)
    if admin?
      project.status.eql?('Published') ? add_ajax_link('Unpublish', project) : add_ajax_link('Publish', project)
    end
  end

  def add_link_to_cancel(project)
    status = project.status
    if admin? && !status.eql?('Expired') && !status.eql?('Completed')
      status.eql?('Canceled') ? add_ajax_link('Reopen', project) : add_ajax_link('Cancel', project)
    end
  end

  def add_ajax_link(text, project)
    link_to text, update_status_project_url(project), class: 'project state btn btn-primary'
  end

  def add_edit_button
    if user_authorized_for_edit?
      concat link_to 'Edit Project', edit_project_url(current_project), data: { disable_with: 'Processing..' }, class: "btn btn-primary"
    end
  end

  def add_donation_fields
    unless created_by_current_user?
      concat text_field_tag :invested_amount, "", project_id: @project.id,
                            minimum: @project.user_minimum_contribution,
                            maximum: @project.user_maximum_contribution,
                            placeholder: "#{@project.user_minimum_contribution} <= amount <= #{@project.user_maximum_contribution}"
      concat "      "
      concat link_to t(:invest), 'javascript:', class: "btn btn-primary", id: 'invest_button', url: new_transaction_for_project_url(@project)
    end
  end

  def insert_delete_image(comment)
    if admin?
      link_to(image_tag("delete-icon", size: '10x10', class: 'delete_image'), comment_url(comment), method: :DELETE,
              data: { disable_with: 'Loading..' }, class: 'delete_comment')
    end
  end

  def add_load_more_button
    offset = params[:offset] ? params[:offset].to_i + 1 : 1
    link_to 'Load More', catagory_projects_url(params[:catagory], offset: offset),
              class: 'load btn btn-primary'
  end

  def get_commentor_name(comment)
    (comment.name && comment.name.humanize) || comment.user.name.humanize
  end

end

app/views/projects/_form.html.erb
<%= content_for :javascript do %>
  <%= javascript_include_tag 'project_form' %>
<% end %>
<table class="table">
  <tr>
    <td><%= f.label :project_kind, t(:project_kind) %></td>
    <td><%= f.select(:kind, Project::TYPES) %></td>
  </tr>
  <tr class="required">
    <td><%= f.label :title, t(:title) %></td>
    <td><%= f.text_field :title, required: true %></td>
  </tr>
  <tr class="required">
    <td><%= f.label :description, t(:description) %></td>
    <td><%= f.text_area :description, cols: 27, rows: 3, required: true %></td>
  </tr>
  <tr class="required">
    <td><%= f.label :end_date, t(:end_Date) %></td>
    <td><%= f.date_field :end_date, required: true %></td>
  </tr>
  <tr class="required">
    <td><%= f.label :total_amount, t(:total_amount) %></td>
    <td><%= f.number_field :total_amount, step: 100, placeholder: 'should be a multiple of 100', required: true %></td>
  </tr>
    <tr class="required">
      <td><%= f.label :images_attributes_0_attachment, t(:images) %></td>
      <td>
        <%= f.fields_for :images do |image_form| %>
          <%= image_tag(image_form.object.attachment.url(:medium)) %>
          <%= image_form.file_field :attachment %>
          <%= image_form.hidden_field(:attachable_subtype, { value: 'image' }) %>
        <% end %>
        <%= link_to t(:add_more), 'javascript:', class: 'upload' %>
      </td>
    </tr>
    <tr class="required">
      <td><%= f.label :documents_attributes_0_attachment, t(:legal_documents) %></td>
      <td>
        <%= f.fields_for :documents do |document_form| %>
          <%= document_form.object.attachment_file_name %>
          <%= document_form.file_field :attachment %>
          <%= document_form.hidden_field(:attachable_subtype, { value: 'document' }) %>
        <% end %>
        <%= link_to t(:add_more), 'javascript:', class: 'upload' %>
      </td>
    </tr>
  <tr>
    <td><%= f.label :video_link, t(:video_link) %></td>
    <td><%= f.url_field :video_link %></td>
  </tr>
  <tr>
    <td><%= f.label :user_minimum_contribution, t(:user_minimum_contribution) %></td>
    <td><%= f.text_field :user_minimum_contribution, readonly: true, placeholder: 'Total Amount / 10' %></td>
  </tr>
</table>

app/views/projects/_row.html.erb
<div class="row">
  <% collection.each do |project| %>
    <% cache project do %>
    	<div class="col-sm-6 col-md-2">
        <div class="thumbnail">
          <a href="<%= project_url(project) %>">
            <img src="<%= project.images.first.attachment.url(:medium) %>">
          </a>
          <div class="caption">
            <a href="<%= project_url(project) %>">
              <b><%= truncate(project.title, length: 12) %></b>
            </a>
            <br>
            <b><%= t(:amount) %>: </b><%= project.total_amount %>
            <hr>
            <%= project.percentage_completed %><%= t(:percentage_completed) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<% content_for :title, 'Edit Project' %>
<%= render partial: 'shared/errors', locals: { form: @project } %>
<%= form_for @project, method: :patch do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit t(:update_project), 'data-disable_with' => 'Updating..' %>
<% end %>

app/views/projects/index.html.erb
<% content_for :title, t(:projects) %>
<% content_for :javascript do %>
  <% javascript_include_tag 'index_page' %>
<% end %>
<div class="new_project" align="center">
  <%= link_to t(:create_new_project), new_project_path %>
</div>
<br>
<% if @projects.present? %>

  <div id="projects">
    <table class="table">
      <tr>
        <th><%= t(:title) %></th>
        <th><%= t(:type) %></th>
        <th><%= t(:total_amount) %></th>
        <th><%= t(:end_date) %></th>
        <th><%= t(:action) %></th>
      </tr>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.kind %></td>
          <td><%= project.total_amount %></td>
          <td><%= project.end_date %></td>
          <td>
            <%= link_to 'show', project_path(project), class: 'btn btn-primary' %>
            <%= add_link_to_publish(project) %>
            <%= add_link_to_cancel(project) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <% if admin? %>
    <% add_pagination(:page_projects_url) %>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<% content_for :title, t(:new_project) %>
<%= render partial: 'shared/errors', locals: { form: @project } %>
<%= form_for @project, method: :put do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit t(:create_project), 'data-disable-with' => 'Processing..' %>
<% end %>

app/views/projects/show.html.erb
<% content_for :title, t(:project) %>
<% content_for :javascript do %>
  <%= javascript_include_tag 'index_page', 'comment', 'slider', 'payment', 'image' %>
<% end %>

<div id="project_details">

  <div class="modal fade bs-example-modal-lg" id="guest_form" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div id="guest_container">
          <%= (render 'sessions/guest_form') unless current_user %>
        </div>
      </div>
    </div>
  </div>

  <% if user_authorized_for_edit? %>
    <div class="notice">
      <p>"Your project is pending for approval. 
        Once it is approved then it will be visible to users"</p>
    </div>
  <% end %>
  
  <div id="project_images">
    <ul class="bxslider">
      <% @project.images.each do |image| %>
        <li class='project_image' id="<%= image.id %>">
          <%= image_tag image.attachment.url(:slider), large: image.attachment.url(:large) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div id="details">
    <table class="table">
    <tr>
      <th><%= t(:type) %></th>
      <td><%= @project.kind %></td>
    </tr>
      <tr>
        <th><%= t(:title) %></th>
        <td><%= @project.title %></td>
      </tr>
      <tr>
        <th><%= t(:description) %></th>
        <td><%= @project.description %></td>
      </tr>
      <tr>
        <th><%= t(:video_link) %></th>
        <td><%= @project.video_link %></td>
      </tr>
      <tr>
        <th><%= t(:total_amount) %></th>
        <td><%= @project.total_amount %></td>
      </tr>
      <tr>
        <th><%= t(:percentage_completed) %></th>
        <td><%= @project.percentage_completed %>%</td>
      </tr>
      <tr>
        <th><%= t(:user_minimum_contribution) %></th>
        <td><%= @project.user_minimum_contribution %></td>
      </tr>
      <% if admin? %>
        <tr>
          <th><%= t(:documents) %></th>
          <td>
            <% @project.documents.each do |doc| %>
              <%= doc.attachment_file_name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <%= add_link_to_publish(@project) %>
  <br><br>
  <% add_edit_button %>
  <% add_donation_fields %>

</div>

<br><br>

<% if admin? && @project.transactions.present? %>
  <div id="contributors">
    <h2 align="center"><%= t(:contributors) %></h2>
    <table class="table">
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t(:email) %></th>
        <th><%= t(:contribution_amount) %></th>
        <th><%= t(:time_of_contribution) %></th>
      </tr>
      <% @project.transactions.each do |contribution| %>
        <tr>
          <td><%= link_to contribution.user.name.humanize, user_url(contribution.user) %></td>
          <td><%= contribution.user.email %></td>
          <td><%= contribution.amount %></td>
          <td><%= contribution.created_at.in_time_zone('Kolkata') %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<br><br>
<div id="comments">
  <H2 align="center"><%= t(:comments) %></H2>
  <br>
  
  <% if current_user %>
    <% @project.comments.each do |comment| %>
      <div class="comment">
        <%= "#{ comment.name || comment.user.name }  - ".capitalize %>
        <%= comment.description %>
        <%= insert_delete_image(comment) %><br>
      </div>
    <% end %>
  <% end %>
  
  <form>
    <%= text_field_tag :comment, "", { placeholder: 'enter comment here', url: comments_url, project_id: @project.id } %>
  </form>

</div>

app/views/projects/view_all.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag :filter %>
<% end %>
<% unless params[:offset] || params[:filter] %>
  <div class="filter">
    <%= t(:filter) %>: <%= select_tag :filter, options_for_select(Project::TYPES), href: catagory_projects_url(params[:catagory]) %>
    <%= t(:sort_by) %>: <%= select_tag :sort_by, options_for_select(["Popularity", "Recent", "Ending at"]), href: catagory_projects_url(params[:catagory]) %>
  </div>
  <br>
  <div id="projects">
<% end %>
  <% if @projects.present? %>
    <% @projects.each_slice(4) do |collection| %>
      <%= render partial: 'row', locals: { collection: collection } %>
    <% end %>
    <div class="see_all">
      <%= add_load_more_button %>
    </div>
  <% else %>
    <div class="notice">
      <p><%= t(:thats_all_folks) %></p>
    </div>
  <% end %>
</div>