config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :passwords, only: [:new, :create, :update] do
    get 'edit', on: :collection
  end

  resources :sessions, only: [:create, :destroy]

  concern :pagination do
    get 'page/:page' => :index, as: :page, on: :collection
  end

  resources :users, except: [:new, :destroy], concerns: :pagination do
    collection do
      get 'account_activation'
      post 'update_state'
    end
    member do
      get 'contribution'
      post 'update_image'
      get 'projects' => 'projects#index'
    end
  end

  resources :projects, concerns: :pagination do
    collection do
      get ':catagory' => :view_all, as: :catagory, 
          constraints: -> (request) { PROJECT_CATAGORIES.include?(request.path_parameters[:catagory]) }
    end
    member do
      post 'update_status'
      scope 'transactions', controller: :transactions do
        post 'new', as: 'new_transaction_for'
        get 'build', as: 'build_transaction_for'
        post 'create', as: 'create_transaction_for'
        get 'success', as: 'success_transaction_for'
      end
    end
  end

  resources :transactions, only: [:index] do
    get 'download_receipt/:stripeToken' => :download_receipt, as: :download_receipt, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  namespace :apis do
    get 'projects' => 'projects#index', defaults: { format: 'JSON' }
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :load_project, only: [:new, :build, :create]
  before_action :authorize_user, :validate_new_request, only: [:new]
  before_action :validate_build_request, only: [:build]
  before_action :charge_card, only: [:create]
  before_action :validate_token, only: [:download_receipt]
  before_action :admin_authorization, only: [:index]

  def index
  end

  def new
    head 200, location: build_transaction_for_project_url(params[:id])
  end

  def build
    render
  end

  def create
    if @project.transactions.create(transaction_params.merge(default_params))
      render 'success'
    else
      flash[:notice] = t(:request_failure)
      redirect_to build_transaction_for_project_url(session[:project_id])
    end
  end

  def download_receipt
    send_data(render_to_string('download_receipt', layout: false), disposition: 'attachment', filename: 'payment_receipt.txt')
  end

private
  
  def admin_authorization
    admin? ? load_transactions : (redirect_to :root, notice: t(:only_admin_can_see))
  end

  def load_transactions
    @transactions = Transaction.all
  end

  def validate_token
    unless @transaction = Transaction.find_by(stripeToken: params[:stripeToken])
      redirect_to :root, notice: t(:invalid_request)
    end
  end

  def charge_card
    begin
      @charge = Stripe::Charge.create(amount: session[:amount], currency: 'usd', source: params[:stripeToken])
    rescue Stripe::CardError, Stripe::InvalidRequestError => error 
      flash[:notice] = error.message
      redirect_to build_transaction_for_project_url(session[:project_id])
    end    
  end

  def authorize_user
    head 401 unless current_user
  end

  def validate_new_request
    if required_params_present?
      session[:amount] = params[:amount].to_i
      session[:project_id] = params[:id]
      check_necessary_documents_presence
    else
      head 400
    end
  end

  def load_project
    @project = Project.find_by(id: params[:id]) if params[:id]
  end

  def required_params_present?
    params[:amount] && @project && params[:amount].to_i >= @project.user_minimum_contribution
  end

  def check_necessary_documents_presence
    unless current_user.profile_complete?
      flash[:notice] = t(:request_profile_completion)
      head 402, location: edit_user_url(current_user)
    end
  end

  def validate_build_request
    redirect_to :root, notice: t(:invalid_request) unless session[:amount] && session[:project_id]
  end

  def default_params
    { status: 'completed', amount: session[:amount], user_id: current_user.id, charge_id: @charge.id }
  end

  def transaction_params
    params.permit(:stripeToken, :stripeEmail, :mode)
  end

end

app/views/transactions/build.html.erb
<form action="<%= create_transaction_for_project_url(@project) %>" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_WMS4wmBseIAKxD1CjAYHcWub"
    data-amount="<%= session[:amount]*100 %>"
    data-name="Crowd Funding"
    data-description="2 widgets ($20.00)"
    data-image="">
  </script>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <%= hidden_field_tag :mode, 'credit card' %>
</form>

app/views/transactions/download_receipt.html.erb
<%= t(:crowd_funding) %>

<%= t(:your_payment_details) %> -

<%= t(:transaction_id) %> : <%= @transaction.id %>
<%= t(:user) %> :
  <%= t(:name) %> : <%= @transaction.user.name.capitalize %>
  <%= t(:email) %> : <%= @transaction.user.email %>
<%= t(:project) %> : <%= @transaction.project.title %>
<%= t(:investment) %> : $<%= @transaction.amount %>

app/views/transactions/index.html.erb
<div id="transactions">
  <h2 align="center">Transactions</h2>
  <table class="table">
    <tr>
      <th><%= t(:email) %></th>
      <th><%= t(:amount) %></th>
      <th><%= t(:payment_mode) %></th>
      <th><%= t(:created_at) %></th>
      <th><%= t(:transaction_id) %></th>
      <th><%= t(:status) %></th>
    </tr>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.stripeEmail %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.mode %></td>
        <td><%= transaction.created_at %></td>
        <td><%= transaction.stripeToken %></td>
        <td><%= transaction.status %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/transactions/success.html.erb
<h3>Thank You for your investment in '<%= @project.title %>'.
We have saved your contribution </h3>
<br>
<%= link_to t(:view_more_projects), :root, class: 'btn btn-primary'  %>&nbsp;&nbsp;
<%= link_to t(:view_all_contributions), contribution_user_path(current_user), class: 'btn btn-primary' %>